name: PartiQL Tests Validator
on: [push, pull_request]

jobs:
  build:
      name: Validate
      runs-on: ubuntu-latest
      strategy:
        matrix:
          java: [8, 11]

      steps:
        - name: Check out code
          uses: actions/checkout@v3

        - name: Setup java ${{ matrix.java }}
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: ${{ matrix.java }}

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Validate Tests
          working-directory: ./partiql-tests-validator
          run: gradle build

        - name: Validate Ported Tests with Kotlin Test Runner
          working-directory: ./partiql-tests-kotlin-test-runner
          run: gradle build

